/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO_controller.DAO;
import Modelos.Empleado;
import OwnAPIs.DataValidation;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sovi8
 */
public class ModificarFrame extends javax.swing.JFrame {

    private Empleado empleado; // Variable para almacenar al empleado
    

    //Constructor que recibe un empleado
    public ModificarFrame(Empleado empleadoBuscado) {
        initComponents();
        this.empleado = empleadoBuscado; // Almaceno el empleado recibido
        LlenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nombre_jLabel1 = new javax.swing.JLabel();
        nombreCompleto_jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreUsuario_jTextField1 = new javax.swing.JTextField();
        nombreCompleto_jTextField3 = new javax.swing.JTextField();
        telefono_jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        id_jTextField1 = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nombre_jLabel1.setText("Nombre Usuario");

        nombreCompleto_jLabel1.setText("Nombre Completo");

        jLabel4.setText("Teléfono");

        jLabel1.setText("Id Empleado");

        id_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreCompleto_jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreCompleto_jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(telefono_jTextField4)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nombre_jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreUsuario_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_jLabel1)
                    .addComponent(nombreUsuario_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCompleto_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCompleto_jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono_jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //  Método para llenar los campos label con los datos del empleado recibido
    private void LlenarCampos(){
        id_jTextField1.setText(String.valueOf(empleado.getId())); 
        nombreUsuario_jTextField1.setText(empleado.getNombreUsuario());
        nombreCompleto_jTextField3.setText(empleado.getNombreCompleto());
        telefono_jTextField4.setText(empleado.getTelefono());

        id_jTextField1.setEditable(false); // Hago que el ID no sea editable
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       DataValidation dataValidation = new DataValidation();
        
       int idEmpleado = empleado.getId();
       
       // Variables que almacenan el input del USR
       String nuevoNombreUsuario = nombreUsuario_jTextField1.getText();
       String nuevoNombreCompleto = nombreCompleto_jTextField3.getText();
       String nuevoTelefono = telefono_jTextField4.getText();
       
       // Creo un objeto de tipo Empleado y le asigno los valores recodigos en el formulario mediante los TextField
        Empleado empleadoModificado = new Empleado();
        empleadoModificado.setId(idEmpleado);
        
        // Compruebo los campos introducidos por el USR
        if(!dataValidation.SolicitaNombreUsuario(nuevoNombreUsuario)){
            return; // Si la validación falla, detengo la ejecución
        }        
        empleadoModificado.setNombreUsuario(nuevoNombreUsuario); // Si el nombre es válido, lo asigno al objeto empleadoModificado
        
        if(!dataValidation.SolicitaNombreCompleto(nuevoNombreCompleto)){
            return;
        }
        empleadoModificado.setNombreCompleto(nuevoNombreCompleto); 
        
        if(!dataValidation.SolicitaTelefono(nuevoTelefono)){
            return;
        }
        empleadoModificado.setTelefono(nuevoTelefono);
       
       // Verifico si los campos están vacíos antes de continuar
        /*if (nuevoNombreUsuario.isEmpty() || nuevoNombreCompleto.isEmpty() || nuevoTelefono.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }*/
        
        try{
             // Creo una instancia de dao y le paso el objeto empleadoModificado
             DAO dao = new DAO();
             dao.ModificarEmpleado(empleadoModificado);
             
             JOptionPane.showMessageDialog(this, "Usuario modificado correctamente.", 
                                  "Éxito", JOptionPane.INFORMATION_MESSAGE);
             
             this.dispose();

        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al buscar el usuario: " + e.getMessage(), 
                                       "Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ModificarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_jTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nombreCompleto_jLabel1;
    private javax.swing.JTextField nombreCompleto_jTextField3;
    private javax.swing.JTextField nombreUsuario_jTextField1;
    private javax.swing.JLabel nombre_jLabel1;
    private javax.swing.JTextField telefono_jTextField4;
    // End of variables declaration//GEN-END:variables
}
