/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Actividad_Tema_2;

import DAO_controller.DAO;
import GUI.InsertarFrame;
import GUI.ModificarContraseñaFrame;
import GUI.ModificarFrame;
import Modelos.Empleado;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sovi8
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();     
        setLocationRelativeTo(null); // Centro la ventana 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear_jButton1 = new javax.swing.JButton();
        modificar_jButton1 = new javax.swing.JButton();
        cambiarContraseña_jButton1 = new javax.swing.JButton();
        eliminar_jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        crear_jButton1.setText("CREAR USUARIO");
        crear_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_jButton1ActionPerformed(evt);
            }
        });

        modificar_jButton1.setText("MODIFICAR PERFIL");
        modificar_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_jButton1ActionPerformed(evt);
            }
        });

        cambiarContraseña_jButton1.setText("CAMBIAR CONTRASEÑA");
        cambiarContraseña_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContraseña_jButton1ActionPerformed(evt);
            }
        });

        eliminar_jButton1.setText("ELIMINAR EMPLEADO");
        eliminar_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crear_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificar_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cambiarContraseña_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminar_jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(crear_jButton1)
                .addGap(18, 18, 18)
                .addComponent(modificar_jButton1)
                .addGap(18, 18, 18)
                .addComponent(cambiarContraseña_jButton1)
                .addGap(18, 18, 18)
                .addComponent(eliminar_jButton1)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crear_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_jButton1ActionPerformed
       
        InsertarFrame insertarFrame = new InsertarFrame(); // Creo una instancia de la nueva ventana
        insertarFrame.setLocationRelativeTo(null); // Centro la ventana
        insertarFrame.setVisible(true); // Muestro la ventana
        
    }//GEN-LAST:event_crear_jButton1ActionPerformed

    private void modificar_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_jButton1ActionPerformed
        
        // Pido que se introduzca el nombre de usuario mediante un JOptionPane
        String nombreUsuario = JOptionPane.showInputDialog(this, "Ingrese el nombre de usuario a modificar: ",
                                                            "Buscar Usuario", JOptionPane.QUESTION_MESSAGE);
        
        // Verifico si el USR cierra la ventana o deja el campo vacío
        if(nombreUsuario == null || nombreUsuario.trim().isEmpty()){
            return;
        }
        
        DAO buscarEmpleado = new DAO(); // Creo una instancia de DAO
        Empleado empleado = null;
        
        try{
           empleado = buscarEmpleado.BuscarEmpleado(nombreUsuario);
           // Compruebo que el objeto Empleado devuelto por el método BuscarEmpleado no sea null
           if(empleado == null){
               JOptionPane.showMessageDialog(null, "No se ha encontrado un usuario con el nombre introducido", 
                                    "Usuario no encontrado", JOptionPane.WARNING_MESSAGE);
                return; 
           }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al buscar el usuario: " + e.getMessage(), 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        ModificarFrame modificarFrame = new ModificarFrame(empleado); // Creo una instancia de la nueva ventana y le paso el objeto empleado encontrado
        modificarFrame.setLocationRelativeTo(null); // Centro la ventana
        modificarFrame.setVisible(true); // Muestro la ventana
    }//GEN-LAST:event_modificar_jButton1ActionPerformed

    private void cambiarContraseña_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContraseña_jButton1ActionPerformed
        // Pido que se introduzca el nombre de usuario
        String nombreUsuario = JOptionPane.showInputDialog(this, "Ingrese el nombre de usuario a modificar: ",
                                                            "Buscar Usuario", JOptionPane.QUESTION_MESSAGE);
         // Verifico si el USR cierra la ventana o deja el campo vacío
        if(nombreUsuario == null || nombreUsuario.trim().isEmpty()){
            return;
        }
        
        DAO buscarEmpleado = new DAO();// Creo una instancia de DAO
        Empleado empleado = null;
        
        try{
           empleado = buscarEmpleado.BuscarEmpleado(nombreUsuario); // Busca el empleado en la base de datos usando el campo nombreUsuario
           // Compruebo que el objeto Empleado devuelto por el método BuscarEmpleado no sea null
           if(empleado == null){
               JOptionPane.showMessageDialog(null, "No se ha encontrado un usuario con el nombre introducido", 
                                    "Usuario no encontrado", JOptionPane.WARNING_MESSAGE);
                return; 
           }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al buscar el usuario: " + e.getMessage(), 
                                      "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        ModificarContraseñaFrame modificarContraseñaFrame = new ModificarContraseñaFrame(empleado);
        modificarContraseñaFrame.setLocationRelativeTo(null);
        modificarContraseñaFrame.setVisible(true);
    }//GEN-LAST:event_cambiarContraseña_jButton1ActionPerformed

    private void eliminar_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_jButton1ActionPerformed
        // Pido que se introduzca el nombre de id del empleado
        String idIntroducido = JOptionPane.showInputDialog(this, "Ingrese el id del empleado a eliminar: ",
                                                            "Eliminar Usuario", JOptionPane.QUESTION_MESSAGE);
        
        // Verifico si el USR cierra la ventana o deja el campo vacío
        if(idIntroducido == null || idIntroducido.trim().isEmpty()){           
            return;
        }
        // Creo una instancia de DAO
        DAO dao = new DAO();
        
        try{         
            int id = Integer.parseInt(idIntroducido); // Parseo el id introducido por el USR
            if(!dao.ExisteEmpleado(id)){ // Compruebo que el id existe en la tabla empleados
                JOptionPane.showMessageDialog(this, "No se ha encontrado ningún empleado con el id proporcionado", "Error", JOptionPane.INFORMATION_MESSAGE);
                return;
                
            }                                                                                                 
            dao.EliminarEmpleado(id); // Elimino el empleado con el id introducido por el USR
            JOptionPane.showMessageDialog(this, "Empleado eliminado exitosamente", "Error", JOptionPane.INFORMATION_MESSAGE);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El ID debe ser numérico", "Error", JOptionPane.ERROR_MESSAGE);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error al intentar eliminar el empleado" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminar_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarContraseña_jButton1;
    private javax.swing.JButton crear_jButton1;
    private javax.swing.JButton eliminar_jButton1;
    private javax.swing.JButton modificar_jButton1;
    // End of variables declaration//GEN-END:variables
}
